/**
 * ApproveAPI
 * The simple API to request a user's approval on anything via email + sms.
 *
 * OpenAPI spec version: 1
 * Contact: dev@approveapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PromptAnswer'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PromptAnswer'));
  } else {
    // Browser globals (root is window)
    if (!root.ApproveapiSwaggerJs) {
      root.ApproveapiSwaggerJs = {};
    }
    root.ApproveapiSwaggerJs.Prompt = factory(root.ApproveapiSwaggerJs.ApiClient, root.ApproveapiSwaggerJs.PromptAnswer);
  }
}(this, function(ApiClient, PromptAnswer) {
  'use strict';




  /**
   * The Prompt model module.
   * @module model/Prompt
   * @version 1
   */

  /**
   * Constructs a new <code>Prompt</code>.
   * @alias module:model/Prompt
   * @class
   * @param id {String} A unique id for this prompt.
   * @param sent_at {Number} The unix timestamp when this prompt was sent.
   */
  var exports = function(id, sent_at) {
    var _this = this;

    _this['id'] = id;
    _this['sent_at'] = sent_at;

  };

  /**
   * Constructs a <code>Prompt</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Prompt} obj Optional instance to populate.
   * @return {module:model/Prompt} The populated <code>Prompt</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('sent_at')) {
        obj['sent_at'] = ApiClient.convertToType(data['sent_at'], 'Number');
      }
      if (data.hasOwnProperty('answer')) {
        obj['answer'] = PromptAnswer.constructFromObject(data['answer']);
      }
    }
    return obj;
  }

  /**
   * A unique id for this prompt.
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * The unix timestamp when this prompt was sent.
   * @member {Number} sent_at
   */
  exports.prototype['sent_at'] = undefined;
  /**
   * The user's answer to this prompt, if there is one.
   * @member {module:model/PromptAnswer} answer
   */
  exports.prototype['answer'] = undefined;



  return exports;
}));


