/**
 * ApproveAPI
 * The simple API to request a user's approval on anything via email + sms.
 *
 * OpenAPI spec version: 1
 * Contact: dev@approveapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ApproveapiSwaggerJs) {
      root.ApproveapiSwaggerJs = {};
    }
    root.ApproveapiSwaggerJs.PromptStatus = factory(root.ApproveapiSwaggerJs.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PromptStatus model module.
   * @module model/PromptStatus
   * @version 1
   */

  /**
   * Constructs a new <code>PromptStatus</code>.
   * @alias module:model/PromptStatus
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>PromptStatus</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PromptStatus} obj Optional instance to populate.
   * @return {module:model/PromptStatus} The populated <code>PromptStatus</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('is_completed')) {
        obj['is_completed'] = ApiClient.convertToType(data['is_completed'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * Whether the prompt has been answered or not.
   * @member {Boolean} is_completed
   */
  exports.prototype['is_completed'] = undefined;



  return exports;
}));


