/**
 * ApproveAPI
 * The simple API to request a user's approval on anything via email + sms.
 *
 * OpenAPI spec version: 1
 * Contact: dev@approveapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApproveapiSwaggerJs);
  }
}(this, function(expect, ApproveapiSwaggerJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApproveapiSwaggerJs.Prompt();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Prompt', function() {
    it('should create an instance of Prompt', function() {
      // uncomment below and update the code to test Prompt
      //var instance = new ApproveapiSwaggerJs.Prompt();
      //expect(instance).to.be.a(ApproveapiSwaggerJs.Prompt);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new ApproveapiSwaggerJs.Prompt();
      //expect(instance).to.be();
    });

    it('should have the property sent_at (base name: "sent_at")', function() {
      // uncomment below and update the code to test the property sent_at
      //var instance = new ApproveapiSwaggerJs.Prompt();
      //expect(instance).to.be();
    });

    it('should have the property answer (base name: "answer")', function() {
      // uncomment below and update the code to test the property answer
      //var instance = new ApproveapiSwaggerJs.Prompt();
      //expect(instance).to.be();
    });

  });

}));
